
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package compiler;

import java.io.*;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Analizador extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Analizador() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Analizador(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Analizador(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\150\000\002\002\004\000\002\004\003\000\002\004" +
    "\003\000\002\006\004\000\002\046\003\000\002\046\004" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\007\003\000\002\007\004\000\002\047\003\000\002" +
    "\047\004\000\002\011\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\004" +
    "\000\002\016\013\000\002\016\012\000\002\017\012\000" +
    "\002\020\012\000\002\021\012\000\002\021\012\000\002" +
    "\077\004\000\002\077\002\000\002\023\003\000\002\023" +
    "\002\000\002\024\003\000\002\024\005\000\002\024\004" +
    "\000\002\025\004\000\002\025\004\000\002\025\004\000" +
    "\002\025\004\000\002\052\003\000\002\052\003\000\002" +
    "\061\004\000\002\060\003\000\002\060\002\000\002\027" +
    "\003\000\002\027\003\000\002\032\004\000\002\050\003" +
    "\000\002\050\004\000\002\033\003\000\002\033\003\000" +
    "\002\033\003\000\002\033\003\000\002\033\006\000\002" +
    "\033\004\000\002\034\003\000\002\034\005\000\002\034" +
    "\003\000\002\051\003\000\002\051\004\000\002\036\003" +
    "\000\002\036\003\000\002\036\003\000\002\036\003\000" +
    "\002\036\003\000\002\036\004\000\002\037\011\000\002" +
    "\037\012\000\002\040\015\000\002\040\017\000\002\064" +
    "\012\000\002\076\003\000\002\076\003\000\002\076\003" +
    "\000\002\067\003\000\002\067\004\000\002\070\006\000" +
    "\002\070\002\000\002\071\007\000\002\071\010\000\002" +
    "\062\005\000\002\062\003\000\002\073\003\000\002\073" +
    "\004\000\002\063\011\000\002\075\006\000\002\100\013" +
    "\000\002\041\003\000\002\041\004\000\002\041\005\000" +
    "\002\056\003\000\002\056\003\000\002\056\003\000\002" +
    "\056\003\000\002\056\003\000\002\056\003\000\002\056" +
    "\003\000\002\056\005\000\002\057\004\000\002\057\005" +
    "\000\002\057\007\000\002\012\011\000\002\013\007\000" +
    "\002\014\007\000\002\015\007\000\002\103\003\000\002" +
    "\103\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\371\000\016\003\022\026\007\032\011\033\005\034" +
    "\023\040\027\001\002\000\020\002\ufff0\003\ufff0\026\ufff0" +
    "\032\ufff0\033\ufff0\034\ufff0\040\ufff0\001\002\000\004\053" +
    "\373\001\002\000\004\002\000\001\002\000\004\053\372" +
    "\001\002\000\016\003\022\026\007\032\011\033\005\034" +
    "\023\040\027\001\002\000\004\053\367\001\002\000\020" +
    "\002\ufff2\003\ufff2\026\ufff2\032\ufff2\033\ufff2\034\ufff2\040" +
    "\ufff2\001\002\000\020\002\ufff6\003\ufff6\026\ufff6\032\ufff6" +
    "\033\ufff6\034\ufff6\040\ufff6\001\002\000\020\002\ufff4\003" +
    "\ufff4\026\ufff4\032\ufff4\033\ufff4\034\ufff4\040\ufff4\001\002" +
    "\000\016\003\ufff8\026\ufff8\032\ufff8\033\ufff8\034\ufff8\040" +
    "\ufff8\001\002\000\016\003\ufffa\026\ufffa\032\ufffa\033\ufffa" +
    "\034\ufffa\040\ufffa\001\002\000\016\003\ufff9\026\ufff9\032" +
    "\ufff9\033\ufff9\034\ufff9\040\ufff9\001\002\000\020\002\uffff" +
    "\003\331\026\326\032\333\033\327\034\332\040\027\001" +
    "\002\000\016\003\ufffd\026\ufffd\032\ufffd\033\ufffd\034\ufffd" +
    "\040\ufffd\001\002\000\006\017\325\024\324\001\002\000" +
    "\004\053\315\001\002\000\016\003\ufffb\026\ufffb\032\ufffb" +
    "\033\ufffb\034\ufffb\040\ufffb\001\002\000\004\002\314\001" +
    "\002\000\020\002\ufff3\003\ufff3\026\ufff3\032\ufff3\033\ufff3" +
    "\034\ufff3\040\ufff3\001\002\000\004\053\031\001\002\000" +
    "\020\002\ufff1\003\ufff1\026\ufff1\032\ufff1\033\ufff1\034\ufff1" +
    "\040\ufff1\001\002\000\004\021\032\001\002\000\016\003" +
    "\037\022\uffe5\026\042\032\041\033\035\034\034\001\002" +
    "\000\004\022\052\001\002\000\004\053\051\001\002\000" +
    "\004\053\050\001\002\000\006\020\046\022\uffe6\001\002" +
    "\000\004\017\045\001\002\000\006\020\uffe4\022\uffe4\001" +
    "\002\000\004\053\044\001\002\000\004\053\043\001\002" +
    "\000\006\020\uffe0\022\uffe0\001\002\000\006\020\uffe1\022" +
    "\uffe1\001\002\000\006\020\uffe2\022\uffe2\001\002\000\012" +
    "\026\042\032\041\033\035\034\034\001\002\000\006\020" +
    "\uffe3\022\uffe3\001\002\000\006\020\uffdf\022\uffdf\001\002" +
    "\000\006\020\uffde\022\uffde\001\002\000\004\023\053\001" +
    "\002\000\030\003\075\025\105\026\055\032\056\033\054" +
    "\034\076\036\066\053\077\061\057\070\063\071\062\001" +
    "\002\000\004\053\206\001\002\000\004\053\206\001\002" +
    "\000\004\053\206\001\002\000\004\021\266\001\002\000" +
    "\026\003\uffc4\017\uffc4\024\uffc4\025\uffc4\036\uffc4\043\uffc4" +
    "\061\uffc4\064\uffc4\070\uffc4\071\uffc4\001\002\000\040\003" +
    "\uffd0\017\uffd0\024\uffd0\025\uffd0\026\uffd0\032\uffd0\033\uffd0" +
    "\034\uffd0\036\uffd0\043\uffd0\053\uffd0\061\uffd0\064\uffd0\070" +
    "\uffd0\071\uffd0\001\002\000\004\021\242\001\002\000\004" +
    "\021\234\001\002\000\030\003\075\025\105\026\055\032" +
    "\056\033\054\034\076\036\066\053\077\061\057\070\063" +
    "\071\062\001\002\000\040\003\uffd2\017\uffd2\024\uffd2\025" +
    "\uffd2\026\uffd2\032\uffd2\033\uffd2\034\uffd2\036\uffd2\043\uffd2" +
    "\053\uffd2\061\uffd2\064\uffd2\070\uffd2\071\uffd2\001\002\000" +
    "\004\023\223\001\002\000\040\003\uffd5\017\uffd5\024\uffd5" +
    "\025\uffd5\026\uffd5\032\uffd5\033\uffd5\034\uffd5\036\uffd5\043" +
    "\uffd5\053\uffd5\061\uffd5\064\uffd5\070\uffd5\071\uffd5\001\002" +
    "\000\026\003\uffca\017\uffca\024\uffca\025\uffca\036\uffca\043" +
    "\uffca\061\uffca\064\uffca\070\uffca\071\uffca\001\002\000\026" +
    "\003\uffc6\017\uffc6\024\uffc6\025\uffc6\036\uffc6\043\uffc6\061" +
    "\uffc6\064\uffc6\070\uffc6\071\uffc6\001\002\000\030\003\uffb2" +
    "\017\uffb2\024\uffb2\025\uffb2\036\uffb2\042\216\043\uffb2\061" +
    "\uffb2\064\uffb2\070\uffb2\071\uffb2\001\002\000\026\003\uffc8" +
    "\017\uffc8\024\uffc8\025\uffc8\036\uffc8\043\uffc8\061\uffc8\064" +
    "\uffc8\070\uffc8\071\uffc8\001\002\000\040\003\uffd1\017\uffd1" +
    "\024\uffd1\025\uffd1\026\uffd1\032\uffd1\033\uffd1\034\uffd1\036" +
    "\uffd1\043\uffd1\053\uffd1\061\uffd1\064\uffd1\070\uffd1\071\uffd1" +
    "\001\002\000\006\017\215\024\150\001\002\000\004\053" +
    "\206\001\002\000\004\014\176\001\002\000\026\003\uffc7" +
    "\017\uffc7\024\uffc7\025\uffc7\036\uffc7\043\uffc7\061\uffc7\064" +
    "\uffc7\070\uffc7\071\uffc7\001\002\000\040\003\uffd3\017\uffd3" +
    "\024\uffd3\025\uffd3\026\uffd3\032\uffd3\033\uffd3\034\uffd3\036" +
    "\uffd3\043\uffd3\053\uffd3\061\uffd3\064\uffd3\070\uffd3\071\uffd3" +
    "\001\002\000\004\024\175\001\002\000\026\003\uffc5\017" +
    "\uffc5\024\uffc5\025\uffc5\036\uffc5\043\uffc5\061\uffc5\064\uffc5" +
    "\070\uffc5\071\uffc5\001\002\000\022\003\147\024\uffd7\025" +
    "\105\036\066\043\uffd7\061\057\070\063\071\062\001\002" +
    "\000\004\021\107\001\002\000\006\024\uffd8\043\uffd8\001" +
    "\002\000\004\053\111\001\002\000\004\017\165\001\002" +
    "\000\006\014\112\017\uffb3\001\002\000\004\031\113\001" +
    "\002\000\004\017\114\001\002\000\024\031\121\035\130" +
    "\045\120\046\127\047\122\050\117\051\116\053\126\063" +
    "\123\001\002\000\004\062\163\001\002\000\010\017\uffa8" +
    "\022\uffa8\062\uffa8\001\002\000\006\017\uffad\022\uffad\001" +
    "\002\000\010\017\uffa4\022\uffa4\062\uffa4\001\002\000\010" +
    "\017\uffaa\022\uffaa\062\uffaa\001\002\000\010\017\uffa9\022" +
    "\uffa9\062\uffa9\001\002\000\004\050\162\001\002\000\004" +
    "\017\133\001\002\000\010\017\uffa7\022\uffa7\062\uffa7\001" +
    "\002\000\010\017\uffa5\022\uffa5\062\uffa5\001\002\000\010" +
    "\017\uffa6\022\uffa6\062\uffa6\001\002\000\004\053\131\001" +
    "\002\000\004\035\132\001\002\000\010\017\uffa3\022\uffa3" +
    "\062\uffa3\001\002\000\004\053\134\001\002\000\010\014" +
    "\154\065\153\067\155\001\002\000\004\022\136\001\002" +
    "\000\004\023\137\001\002\000\032\003\075\024\uffd9\025" +
    "\105\026\055\032\056\033\054\034\076\036\066\053\077" +
    "\061\057\070\063\071\062\001\002\000\012\017\uffdc\024" +
    "\uffdc\043\uffdc\064\uffdc\001\002\000\040\003\075\017\uffd9" +
    "\024\uffd9\025\105\026\055\032\056\033\054\034\076\036" +
    "\066\043\uffd9\053\077\061\057\064\uffd9\070\063\071\062" +
    "\001\002\000\012\017\uffdd\024\uffdd\043\uffdd\064\uffdd\001" +
    "\002\000\026\003\147\017\uffda\024\uffda\025\105\036\066" +
    "\043\uffda\061\057\064\uffda\070\063\071\062\001\002\000" +
    "\004\024\145\001\002\000\026\003\uffbf\017\uffbf\024\uffbf" +
    "\025\uffbf\036\uffbf\043\uffbf\061\uffbf\064\uffbf\070\uffbf\071" +
    "\uffbf\001\002\000\026\003\uffc9\017\uffc9\024\uffc9\025\uffc9" +
    "\036\uffc9\043\uffc9\061\uffc9\064\uffc9\070\uffc9\071\uffc9\001" +
    "\002\000\004\024\150\001\002\000\026\003\uffc3\017\uffc3" +
    "\024\uffc3\025\uffc3\036\uffc3\043\uffc3\061\uffc3\064\uffc3\070" +
    "\uffc3\071\uffc3\001\002\000\012\017\uffdb\024\uffdb\043\uffdb" +
    "\064\uffdb\001\002\000\040\003\uffd4\017\uffd4\024\uffd4\025" +
    "\uffd4\026\uffd4\032\uffd4\033\uffd4\034\uffd4\036\uffd4\043\uffd4" +
    "\053\uffd4\061\uffd4\064\uffd4\070\uffd4\071\uffd4\001\002\000" +
    "\004\022\uffa2\001\002\000\004\053\157\001\002\000\004" +
    "\031\156\001\002\000\004\022\uffa1\001\002\000\004\066" +
    "\160\001\002\000\004\031\161\001\002\000\004\022\uffa0" +
    "\001\002\000\006\017\uffac\022\uffac\001\002\000\020\031" +
    "\121\035\130\045\120\046\127\047\122\051\116\053\126" +
    "\001\002\000\006\017\uffab\022\uffab\001\002\000\024\031" +
    "\121\035\130\045\120\046\127\047\122\050\117\051\116" +
    "\053\126\063\123\001\002\000\004\017\167\001\002\000" +
    "\004\053\134\001\002\000\004\022\171\001\002\000\004" +
    "\023\172\001\002\000\032\003\075\024\uffd9\025\105\026" +
    "\055\032\056\033\054\034\076\036\066\053\077\061\057" +
    "\070\063\071\062\001\002\000\004\024\174\001\002\000" +
    "\026\003\uffc0\017\uffc0\024\uffc0\025\uffc0\036\uffc0\043\uffc0" +
    "\061\uffc0\064\uffc0\070\uffc0\071\uffc0\001\002\000\020\002" +
    "\uffe9\003\uffe9\026\uffe9\032\uffe9\033\uffe9\034\uffe9\040\uffe9" +
    "\001\002\000\010\031\201\035\177\045\202\001\002\000" +
    "\004\053\204\001\002\000\004\017\203\001\002\000\004" +
    "\017\uffcd\001\002\000\004\017\uffcb\001\002\000\040\003" +
    "\uffcf\017\uffcf\024\uffcf\025\uffcf\026\uffcf\032\uffcf\033\uffcf" +
    "\034\uffcf\036\uffcf\043\uffcf\053\uffcf\061\uffcf\064\uffcf\070" +
    "\uffcf\071\uffcf\001\002\000\004\035\205\001\002\000\004" +
    "\017\uffcc\001\002\000\006\014\uff9b\020\uff9b\001\002\000" +
    "\006\014\211\020\210\001\002\000\004\053\214\001\002" +
    "\000\004\031\212\001\002\000\004\017\213\001\002\000" +
    "\042\003\uff9c\017\uff9c\024\uff9c\025\uff9c\026\uff9c\032\uff9c" +
    "\033\uff9c\034\uff9c\036\uff9c\040\uff9c\043\uff9c\053\uff9c\061" +
    "\uff9c\064\uff9c\070\uff9c\071\uff9c\001\002\000\006\014\uff9a" +
    "\020\uff9a\001\002\000\040\003\uffce\017\uffce\024\uffce\025" +
    "\uffce\026\uffce\032\uffce\033\uffce\034\uffce\036\uffce\043\uffce" +
    "\053\uffce\061\uffce\064\uffce\070\uffce\071\uffce\001\002\000" +
    "\004\023\220\001\002\000\026\003\uffb1\017\uffb1\024\uffb1" +
    "\025\uffb1\036\uffb1\043\uffb1\061\uffb1\064\uffb1\070\uffb1\071" +
    "\uffb1\001\002\000\032\003\075\024\uffd9\025\105\026\055" +
    "\032\056\033\054\034\076\036\066\053\077\061\057\070" +
    "\063\071\062\001\002\000\004\024\222\001\002\000\026" +
    "\003\uffaf\017\uffaf\024\uffaf\025\uffaf\036\uffaf\043\uffaf\061" +
    "\uffaf\064\uffaf\070\uffaf\071\uffaf\001\002\000\032\003\075" +
    "\024\uffd9\025\105\026\055\032\056\033\054\034\076\036" +
    "\066\053\077\061\057\070\063\071\062\001\002\000\004" +
    "\024\225\001\002\000\004\061\226\001\002\000\004\021" +
    "\227\001\002\000\024\031\121\035\130\045\120\046\127" +
    "\047\122\050\117\051\116\053\126\063\123\001\002\000" +
    "\004\022\231\001\002\000\004\017\232\001\002\000\026" +
    "\003\uffae\017\uffae\024\uffae\025\uffae\036\uffae\043\uffae\061" +
    "\uffae\064\uffae\070\uffae\071\uffae\001\002\000\022\003\147" +
    "\024\uffd6\025\105\036\066\043\uffd6\061\057\070\063\071" +
    "\062\001\002\000\024\031\121\035\130\045\120\046\127" +
    "\047\122\050\117\051\116\053\126\063\123\001\002\000" +
    "\004\022\236\001\002\000\004\023\237\001\002\000\032" +
    "\003\075\024\uffd9\025\105\026\055\032\056\033\054\034" +
    "\076\036\066\053\077\061\057\070\063\071\062\001\002" +
    "\000\004\024\241\001\002\000\030\003\uffb0\017\uffb0\024" +
    "\uffb0\025\uffb0\036\uffb0\042\uffb0\043\uffb0\061\uffb0\064\uffb0" +
    "\070\uffb0\071\uffb0\001\002\000\004\053\243\001\002\000" +
    "\004\022\244\001\002\000\004\023\245\001\002\000\004" +
    "\072\250\001\002\000\010\024\uffba\072\uffba\073\uffba\001" +
    "\002\000\010\024\uffb7\072\250\073\257\001\002\000\004" +
    "\031\251\001\002\000\004\074\252\001\002\000\034\003" +
    "\075\017\uffd9\025\105\026\055\032\056\033\054\034\076" +
    "\036\066\053\077\061\057\064\uffd9\070\063\071\062\001" +
    "\002\000\006\017\255\064\254\001\002\000\004\017\256" +
    "\001\002\000\010\024\uffb6\072\uffb6\073\uffb6\001\002\000" +
    "\010\024\uffb5\072\uffb5\073\uffb5\001\002\000\004\074\263" +
    "\001\002\000\004\024\262\001\002\000\010\024\uffb9\072" +
    "\uffb9\073\uffb9\001\002\000\026\003\uffbe\017\uffbe\024\uffbe" +
    "\025\uffbe\036\uffbe\043\uffbe\061\uffbe\064\uffbe\070\uffbe\071" +
    "\uffbe\001\002\000\032\003\075\017\uffd9\025\105\026\055" +
    "\032\056\033\054\034\076\036\066\053\077\061\057\070" +
    "\063\071\062\001\002\000\004\017\265\001\002\000\004" +
    "\024\uffb8\001\002\000\024\031\121\035\130\045\120\046" +
    "\127\047\122\050\117\051\116\053\126\063\123\001\002" +
    "\000\004\022\270\001\002\000\004\023\271\001\002\000" +
    "\034\003\075\024\uffd9\025\105\026\055\032\056\033\054" +
    "\034\076\036\066\043\uffd9\053\077\061\057\070\063\071" +
    "\062\001\002\000\006\024\274\043\273\001\002\000\004" +
    "\024\275\001\002\000\026\003\uffc2\017\uffc2\024\uffc2\025" +
    "\uffc2\036\uffc2\043\uffc2\061\uffc2\064\uffc2\070\uffc2\071\uffc2" +
    "\001\002\000\026\003\uffc1\017\uffc1\024\uffc1\025\uffc1\036" +
    "\uffc1\043\uffc1\061\uffc1\064\uffc1\070\uffc1\071\uffc1\001\002" +
    "\000\006\014\277\020\210\001\002\000\004\035\300\001" +
    "\002\000\004\053\301\001\002\000\004\035\302\001\002" +
    "\000\004\017\303\001\002\000\042\003\uff9f\017\uff9f\024" +
    "\uff9f\025\uff9f\026\uff9f\032\uff9f\033\uff9f\034\uff9f\036\uff9f" +
    "\040\uff9f\043\uff9f\053\uff9f\061\uff9f\064\uff9f\070\uff9f\071" +
    "\uff9f\001\002\000\006\014\305\020\210\001\002\000\004" +
    "\031\306\001\002\000\004\017\307\001\002\000\042\003" +
    "\uff9e\017\uff9e\024\uff9e\025\uff9e\026\uff9e\032\uff9e\033\uff9e" +
    "\034\uff9e\036\uff9e\040\uff9e\043\uff9e\053\uff9e\061\uff9e\064" +
    "\uff9e\070\uff9e\071\uff9e\001\002\000\006\014\311\020\210" +
    "\001\002\000\004\045\312\001\002\000\004\017\313\001" +
    "\002\000\042\003\uff9d\017\uff9d\024\uff9d\025\uff9d\026\uff9d" +
    "\032\uff9d\033\uff9d\034\uff9d\036\uff9d\040\uff9d\043\uff9d\053" +
    "\uff9d\061\uff9d\064\uff9d\070\uff9d\071\uff9d\001\002\000\004" +
    "\002\001\001\002\000\010\014\uff9b\020\uff9b\021\316\001" +
    "\002\000\016\003\037\022\uffe5\026\042\032\041\033\035" +
    "\034\034\001\002\000\004\022\320\001\002\000\004\023" +
    "\321\001\002\000\030\003\075\025\105\026\055\032\056" +
    "\033\054\034\076\036\066\053\077\061\057\070\063\071" +
    "\062\001\002\000\004\024\323\001\002\000\020\002\uffea" +
    "\003\uffea\026\uffea\032\uffea\033\uffea\034\uffea\040\uffea\001" +
    "\002\000\020\002\uffef\003\uffef\026\uffef\032\uffef\033\uffef" +
    "\034\uffef\040\uffef\001\002\000\016\003\ufff7\026\ufff7\032" +
    "\ufff7\033\ufff7\034\ufff7\040\ufff7\001\002\000\004\053\360" +
    "\001\002\000\004\053\351\001\002\000\020\002\ufff5\003" +
    "\ufff5\026\ufff5\032\ufff5\033\ufff5\034\ufff5\040\ufff5\001\002" +
    "\000\004\024\324\001\002\000\004\053\350\001\002\000" +
    "\004\053\334\001\002\000\004\021\335\001\002\000\016" +
    "\003\037\022\uffe5\026\042\032\041\033\035\034\034\001" +
    "\002\000\004\022\337\001\002\000\004\023\340\001\002" +
    "\000\034\003\075\024\uffe7\025\105\026\055\032\056\033" +
    "\054\034\076\036\066\043\341\053\077\061\057\070\063" +
    "\071\062\001\002\000\004\017\347\001\002\000\004\024" +
    "\346\001\002\000\006\024\uffe7\043\341\001\002\000\004" +
    "\024\345\001\002\000\020\002\uffee\003\uffee\026\uffee\032" +
    "\uffee\033\uffee\034\uffee\040\uffee\001\002\000\020\002\uffed" +
    "\003\uffed\026\uffed\032\uffed\033\uffed\034\uffed\040\uffed\001" +
    "\002\000\004\024\uffe8\001\002\000\004\021\316\001\002" +
    "\000\004\021\352\001\002\000\016\003\037\022\uffe5\026" +
    "\042\032\041\033\035\034\034\001\002\000\004\022\354" +
    "\001\002\000\004\023\355\001\002\000\030\003\075\025" +
    "\105\026\055\032\056\033\054\034\076\036\066\053\077" +
    "\061\057\070\063\071\062\001\002\000\004\024\357\001" +
    "\002\000\020\002\uffeb\003\uffeb\026\uffeb\032\uffeb\033\uffeb" +
    "\034\uffeb\040\uffeb\001\002\000\004\021\361\001\002\000" +
    "\016\003\037\022\uffe5\026\042\032\041\033\035\034\034" +
    "\001\002\000\004\022\363\001\002\000\004\023\364\001" +
    "\002\000\030\003\075\025\105\026\055\032\056\033\054" +
    "\034\076\036\066\053\077\061\057\070\063\071\062\001" +
    "\002\000\004\024\366\001\002\000\020\002\uffec\003\uffec" +
    "\026\uffec\032\uffec\033\uffec\034\uffec\040\uffec\001\002\000" +
    "\010\014\uff9b\020\uff9b\021\335\001\002\000\016\003\ufffc" +
    "\026\ufffc\032\ufffc\033\ufffc\034\ufffc\040\ufffc\001\002\000" +
    "\020\002\ufffe\003\331\026\326\032\333\033\327\034\332" +
    "\040\027\001\002\000\010\014\uff9b\020\uff9b\021\361\001" +
    "\002\000\010\014\uff9b\020\uff9b\021\352\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\371\000\040\004\024\006\005\007\020\011\012\012" +
    "\023\013\015\014\016\015\014\016\013\017\025\020\011" +
    "\021\027\022\003\046\007\047\017\001\001\000\002\001" +
    "\001\000\004\103\307\001\001\000\002\001\001\000\004" +
    "\103\303\001\001\000\032\007\367\011\012\012\023\013" +
    "\015\014\016\015\014\016\013\017\025\020\011\021\027" +
    "\022\003\047\370\001\001\000\004\103\275\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\011" +
    "\327\016\013\017\025\020\011\021\027\022\003\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\103\206\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\023\032\024\035\025\037\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\025\046\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\042\012" +
    "\100\013\064\014\073\015\060\027\101\032\105\033\066" +
    "\036\067\037\072\040\077\050\063\051\103\063\071\064" +
    "\102\073\070\100\057\001\001\000\004\103\307\001\001" +
    "\000\004\103\303\001\001\000\004\103\275\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\034\012\100\013\064\014" +
    "\073\015\060\033\151\036\067\037\072\040\077\051\232" +
    "\063\071\064\102\073\070\100\057\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\075\216\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\103\206" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\020\036\145" +
    "\037\072\040\077\063\071\064\102\073\070\100\057\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\062\107" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\041\123\055\124\056\114" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\057\134\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\044" +
    "\012\100\013\064\014\073\015\060\033\066\036\067\037" +
    "\072\040\077\050\140\051\142\052\143\060\137\061\141" +
    "\063\071\064\102\073\070\100\057\001\001\000\002\001" +
    "\001\000\036\012\100\013\064\014\073\015\060\033\151" +
    "\036\067\037\072\040\077\051\142\060\150\063\071\064" +
    "\102\073\070\100\057\001\001\000\002\001\001\000\020" +
    "\036\145\037\072\040\077\063\071\064\102\073\070\100" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\055\124\056\163\001\001\000\002\001\001\000\010\041" +
    "\165\055\124\056\114\001\001\000\002\001\001\000\004" +
    "\057\167\001\001\000\002\001\001\000\002\001\001\000" +
    "\044\012\100\013\064\014\073\015\060\033\066\036\067" +
    "\037\072\040\077\050\140\051\142\052\172\060\137\061" +
    "\141\063\071\064\102\073\070\100\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\034" +
    "\177\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\044\012\100\013\064\014" +
    "\073\015\060\033\066\036\067\037\072\040\077\050\140" +
    "\051\142\052\220\060\137\061\141\063\071\064\102\073" +
    "\070\100\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\044\012\100\013\064\014\073\015\060\033\066\036" +
    "\067\037\072\040\077\050\140\051\142\052\223\060\137" +
    "\061\141\063\071\064\102\073\070\100\057\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\041\227\055\124\056\114\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\036\145\037\072" +
    "\040\077\063\071\064\102\073\070\100\057\001\001\000" +
    "\010\041\234\055\124\056\114\001\001\000\002\001\001" +
    "\000\002\001\001\000\044\012\100\013\064\014\073\015" +
    "\060\033\066\036\067\037\072\040\077\050\140\051\142" +
    "\052\237\060\137\061\141\063\071\064\102\073\070\100" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\067" +
    "\246\071\245\001\001\000\002\001\001\000\006\070\257" +
    "\071\260\001\001\000\002\001\001\000\002\001\001\000" +
    "\044\012\100\013\064\014\073\015\060\033\066\036\067" +
    "\037\072\040\077\050\140\051\142\052\252\060\137\061" +
    "\141\063\071\064\102\073\070\100\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\044\012\100\013\064\014\073\015" +
    "\060\033\066\036\067\037\072\040\077\050\140\051\142" +
    "\052\263\060\137\061\141\063\071\064\102\073\070\100" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\041\266\055\124\056\114\001\001\000\002\001\001\000" +
    "\002\001\001\000\044\012\100\013\064\014\073\015\060" +
    "\033\066\036\067\037\072\040\077\050\140\051\142\052" +
    "\271\060\137\061\141\063\071\064\102\073\070\100\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\023\316\024\035\025\037\001" +
    "\001\000\002\001\001\000\002\001\001\000\042\012\100" +
    "\013\064\014\073\015\060\027\321\032\105\033\066\036" +
    "\067\037\072\040\077\050\063\051\103\063\071\064\102" +
    "\073\070\100\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\023\335\024\035\025\037\001\001\000\002\001\001\000" +
    "\002\001\001\000\044\012\100\013\064\014\073\015\060" +
    "\027\342\032\105\033\066\036\067\037\072\040\077\050" +
    "\063\051\103\063\071\064\102\073\070\077\341\100\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\077" +
    "\343\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\023\352\024\035\025\037\001\001\000\002" +
    "\001\001\000\002\001\001\000\042\012\100\013\064\014" +
    "\073\015\060\027\355\032\105\033\066\036\067\037\072" +
    "\040\077\050\063\051\103\063\071\064\102\073\070\100" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\023\361\024\035\025\037\001\001\000" +
    "\002\001\001\000\002\001\001\000\042\012\100\013\064" +
    "\014\073\015\060\027\364\032\105\033\066\036\067\037" +
    "\072\040\077\050\063\051\103\063\071\064\102\073\070" +
    "\100\057\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\011\327\016\013" +
    "\017\025\020\011\021\027\022\003\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Analizador$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Analizador$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Analizador$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public static void main(String args[]) throws Exception{
		//new parser(new Yylex(new FileInputStream(args[0]))).parse();
                Reader reader = new FileReader("src\\compiler\\entrada.txt");
		new Analizador(new Yylex(reader)).parse();
	}
	
        public void syntax_error(Symbol s){
            System.out.println("Error sintactico en la sentencia");
            System.out.println("La Cadena: " + s.value+" en la Linea: " + (s.right+1) +" ,Columna: "+s.left+ " esta fuera de contexto." );
        }

        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
            System.out.println("Error sintactico en la sentencia");
            System.out.println("La Cadena: " + s.value+" en la Linea: " + (s.right+1) +" ,Columna: "+s.left+ " esta fuera de contexto." );
        }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Analizador$actions {
  private final Analizador parser;

  /** Constructor */
  CUP$Analizador$actions(Analizador parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Analizador$do_action_part00000000(
    int                        CUP$Analizador$act_num,
    java_cup.runtime.lr_parser CUP$Analizador$parser,
    java.util.Stack            CUP$Analizador$stack,
    int                        CUP$Analizador$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Analizador$result;

      /* select the action based on the action number */
      switch (CUP$Analizador$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= begin EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)).value;
		RESULT = start_val;
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Analizador$parser.done_parsing();
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // begin ::= globals 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("begin",2, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // begin ::= list_functions 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("begin",2, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // globals ::= list_globals list_functions 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("globals",4, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // list_globals ::= global 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_globals",36, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // list_globals ::= list_globals global 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_globals",36, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // global ::= type_char 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("global",5, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // global ::= type_int 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("global",5, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // global ::= type_long 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("global",5, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // global ::= type_short 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("global",5, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // global ::= error PYCOMA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("global",5, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // list_functions ::= function 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_functions",37, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // list_functions ::= list_functions function 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_functions",37, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // function ::= function_char 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function",7, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // function ::= function_int 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function",7, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // function ::= function_long 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function",7, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // function ::= function_short 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function",7, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // function ::= function_void 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function",7, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // function ::= error LLAVEDER 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function",7, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // function_char ::= CHAR IDENTIFICADOR PARIZQ parametros_otp PARDER LLAVEIZQ cuerpo_function return LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("si, function char"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function_char",12, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-8)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // function_char ::= CHAR IDENTIFICADOR PARIZQ parametros_otp PARDER LLAVEIZQ return LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("si, function char"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function_char",12, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-7)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // function_int ::= INT IDENTIFICADOR PARIZQ parametros_otp PARDER LLAVEIZQ cuerpo_function LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("si, function int"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function_int",13, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-7)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // function_long ::= LONG IDENTIFICADOR PARIZQ parametros_otp PARDER LLAVEIZQ cuerpo_function LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("si, function long"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function_long",14, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-7)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // function_short ::= SHORT IDENTIFICADOR PARIZQ parametros_otp PARDER LLAVEIZQ cuerpo_function LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("si, function short"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function_short",15, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-7)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // function_short ::= VOID IDENTIFICADOR PARIZQ parametros_otp PARDER LLAVEIZQ cuerpo_function LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("si, function void"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("function_short",15, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-7)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // return ::= RETURN PYCOMA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("return",61, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // return ::= 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("return",61, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // parametros_otp ::= parametros 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("parametros_otp",17, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // parametros_otp ::= 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("parametros_otp",17, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // parametros ::= parametro 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("parametros",18, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // parametros ::= parametros COMA parametro 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("parametros",18, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-2)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // parametros ::= error PYCOMA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("parametros",18, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // parametro ::= CHAR IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("parametro",19, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // parametro ::= INT IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("parametro",19, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // parametro ::= LONG IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("parametro",19, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // parametro ::= SHORT IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("parametro",19, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // cuerpo_sentencia ::= declaraciones_estruct 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("cuerpo_sentencia",40, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // cuerpo_sentencia ::= list_sentencias_estruct 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("cuerpo_sentencia",40, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // declaraciones_estruct ::= list_declaraciones list_sentencias_estruct 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("declaraciones_estruct",47, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // list_sentencias_estruct ::= list_sentencias 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_sentencias_estruct",46, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // list_sentencias_estruct ::= 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_sentencias_estruct",46, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // cuerpo_function ::= declaraciones 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("cuerpo_function",21, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // cuerpo_function ::= list_sentencias 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("cuerpo_function",21, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // declaraciones ::= list_declaraciones list_sentencias 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("declaraciones",24, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // list_declaraciones ::= declaracion 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_declaraciones",38, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // list_declaraciones ::= list_declaraciones declaracion 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_declaraciones",38, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // declaracion ::= type_char 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("declaracion",25, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // declaracion ::= type_int 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("declaracion",25, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // declaracion ::= type_long 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("declaracion",25, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // declaracion ::= type_short 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("declaracion",25, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // declaracion ::= IDENTIFICADOR IGUAL type PYCOMA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("declaracion",25, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-3)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // declaracion ::= error PYCOMA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("declaracion",25, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // type ::= LITERALDECIMAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type",26, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // type ::= COMILLA IDENTIFICADOR COMILLA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type",26, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-2)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // type ::= LITERALPTOFLOTANTE 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type",26, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // list_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_sentencias",39, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // list_sentencias ::= list_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("list_sentencias",39, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // sentencia ::= while 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("sentencia",28, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // sentencia ::= for 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("sentencia",28, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // sentencia ::= ifelse 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("sentencia",28, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // sentencia ::= switch 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("sentencia",28, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // sentencia ::= dowhile 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("sentencia",28, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // sentencia ::= error LLAVEDER 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("sentencia",28, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // while ::= WHILE PARIZQ condicion PARDER LLAVEIZQ cuerpo_sentencia LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("Siii, while"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("while",29, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-6)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // while ::= WHILE PARIZQ condicion PARDER LLAVEIZQ cuerpo_sentencia RETURN LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("Siii, while"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("while",29, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-7)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // for ::= FOR PARIZQ first_for PYCOMA condicion PYCOMA operacion PARDER LLAVEIZQ cuerpo_sentencia LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("Siii, for"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("for",30, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-10)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // for ::= FOR PARIZQ IDENTIFICADOR IGUAL LITERALDECIMAL PYCOMA condicion PYCOMA operacion PARDER LLAVEIZQ cuerpo_sentencia LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("Siii, for"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("for",30, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-12)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // switch ::= SWITCH PARIZQ IDENTIFICADOR PARDER LLAVEIZQ cases default LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("si, Switch"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("switch",50, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-7)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expression ::= LITERALDECIMAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("expression",60, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expression ::= LITERALOCTAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("expression",60, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expression ::= LITERALHEXADECIMAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("expression",60, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // cases ::= case 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("cases",53, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // cases ::= cases case 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("cases",53, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // default ::= DEFAULT DOSPUNTOS cuerpo_sentencia PYCOMA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("default",54, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-3)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // default ::= 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("default",54, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // case ::= CASE LITERALDECIMAL DOSPUNTOS cuerpo_sentencia PYCOMA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("case",55, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-4)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // case ::= CASE LITERALDECIMAL DOSPUNTOS cuerpo_sentencia BREAK PYCOMA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("case",55, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-5)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // first_for ::= IDENTIFICADOR IGUAL LITERALDECIMAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("first_for",48, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-2)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // first_for ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("first_for",48, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // ifelse ::= if 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("ifelse",57, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // ifelse ::= if else 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("ifelse",57, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // if ::= IF PARIZQ condicion PARDER LLAVEIZQ cuerpo_sentencia LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("Siii, IIIF"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("if",49, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-6)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // else ::= ELSE LLAVEIZQ cuerpo_sentencia LLAVEDER 
            {
              Object RESULT =null;
		 System.out.println("Siii, ifelse"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("else",59, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-3)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // dowhile ::= DO LLAVEIZQ cuerpo_sentencia LLAVEDER WHILE PARIZQ condicion PARDER PYCOMA 
            {
              Object RESULT =null;
		 System.out.println("Siii, DoWhile"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("dowhile",62, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-8)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // condicion ::= LITERALBOOLEANO 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("condicion",31, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // condicion ::= NEGADO LITERALBOOLEANO 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("condicion",31, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // condicion ::= type_Cond LISTABOOLEANOS type_Cond 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("condicion",31, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-2)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // type_Cond ::= LITERALDECIMAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_Cond",44, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // type_Cond ::= LITERALOCTAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_Cond",44, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // type_Cond ::= LITERALHEXADECIMAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_Cond",44, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // type_Cond ::= booleano 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_Cond",44, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // type_Cond ::= LITERALSTRING 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_Cond",44, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // type_Cond ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_Cond",44, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // type_Cond ::= LITERALPTOFLOTANTE 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_Cond",44, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // type_Cond ::= COMILLA IDENTIFICADOR COMILLA 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_Cond",44, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-2)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // operacion ::= IDENTIFICADOR INC_DEC 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("operacion",45, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-1)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // operacion ::= IDENTIFICADOR OPERADORCOMBINADO LITERALDECIMAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("operacion",45, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-2)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // operacion ::= IDENTIFICADOR IGUAL IDENTIFICADOR OPERADORSIMPLE LITERALDECIMAL 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("operacion",45, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-4)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // type_char ::= CHAR identificadores IGUAL COMILLA IDENTIFICADOR COMILLA PYCOMA 
            {
              Object RESULT =null;
		 System.out.println("si, global char"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_char",8, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-6)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // type_int ::= INT identificadores IGUAL LITERALDECIMAL PYCOMA 
            {
              Object RESULT =null;
		 System.out.println("si, global int"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_int",9, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-4)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // type_long ::= LONG identificadores IGUAL LITERALPTOFLOTANTE PYCOMA 
            {
              Object RESULT =null;
		 System.out.println("si, global long"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_long",10, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-4)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // type_short ::= SHORT identificadores IGUAL LITERALDECIMAL PYCOMA 
            {
              Object RESULT =null;
		 System.out.println("si, global short"); 
              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("type_short",11, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-4)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // identificadores ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("identificadores",65, ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // identificadores ::= identificadores COMA IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Analizador$result = parser.getSymbolFactory().newSymbol("identificadores",65, ((java_cup.runtime.Symbol)CUP$Analizador$stack.elementAt(CUP$Analizador$top-2)), ((java_cup.runtime.Symbol)CUP$Analizador$stack.peek()), RESULT);
            }
          return CUP$Analizador$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Analizador$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Analizador$do_action(
    int                        CUP$Analizador$act_num,
    java_cup.runtime.lr_parser CUP$Analizador$parser,
    java.util.Stack            CUP$Analizador$stack,
    int                        CUP$Analizador$top)
    throws java.lang.Exception
    {
              return CUP$Analizador$do_action_part00000000(
                               CUP$Analizador$act_num,
                               CUP$Analizador$parser,
                               CUP$Analizador$stack,
                               CUP$Analizador$top);
    }
}

}
