
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 22;
  public static final int SHORT = 26;
  public static final int LITERALNULL = 31;
  public static final int LITERALPTOFLOTANTE = 32;
  public static final int CHAR = 24;
  public static final int LITERALDECIMAL = 23;
  public static final int DIFERENTE = 2;
  public static final int LLAVEDER = 18;
  public static final int INT = 20;
  public static final int SEPARADOR = 38;
  public static final int FOR = 19;
  public static final int IDENTIFICADOR = 37;
  public static final int MENORIGUAL = 4;
  public static final int IGUAL = 10;
  public static final int LITERALBOOLEANO = 30;
  public static final int MENOSNUM = 5;
  public static final int MASNUM = 8;
  public static final int ID = 21;
  public static final int MAYORIGUAL = 3;
  public static final int PYCOMA = 13;
  public static final int EOF = 0;
  public static final int PARIZQ = 15;
  public static final int error = 1;
  public static final int COMILLA = 27;
  public static final int COMA = 14;
  public static final int MENOR = 12;
  public static final int RESERVADA = 36;
  public static final int VOID = 29;
  public static final int LITERALOCTAL = 34;
  public static final int ERROR = 40;
  public static final int PCOMA = 28;
  public static final int IMPORT = 42;
  public static final int MAYOR = 11;
  public static final int LITERALSTRING = 33;
  public static final int OPERADOR = 39;
  public static final int PACKAGE = 41;
  public static final int WHILE = 43;
  public static final int LLAVEIZQ = 17;
  public static final int MENOSUNO = 6;
  public static final int LONG = 25;
  public static final int LITERALHEXADECIMAL = 35;
  public static final int MASUNO = 9;
  public static final int TERMINAL = 7;
  public static final int PARDER = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DIFERENTE",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MENOSNUM",
  "MENOSUNO",
  "TERMINAL",
  "MASNUM",
  "MASUNO",
  "IGUAL",
  "MAYOR",
  "MENOR",
  "PYCOMA",
  "COMA",
  "PARIZQ",
  "PARDER",
  "LLAVEIZQ",
  "LLAVEDER",
  "FOR",
  "INT",
  "ID",
  "NUMERO",
  "LITERALDECIMAL",
  "CHAR",
  "LONG",
  "SHORT",
  "COMILLA",
  "PCOMA",
  "VOID",
  "LITERALBOOLEANO",
  "LITERALNULL",
  "LITERALPTOFLOTANTE",
  "LITERALSTRING",
  "LITERALOCTAL",
  "LITERALHEXADECIMAL",
  "RESERVADA",
  "IDENTIFICADOR",
  "SEPARADOR",
  "OPERADOR",
  "ERROR",
  "PACKAGE",
  "IMPORT",
  "WHILE"
  };
}

