
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVI = 8;
  public static final int MENOS = 7;
  public static final int NUMBER = 9;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int TIMES = 4;
  public static final int LPAREN = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "MENOS",
  "DIVI",
  "NUMBER"
  };
}

